import {
  readMatrix,
  readToolchains,
  renderMatrix,
  renderToolchain,
} from '../src/lib/docs/compat.ts';
import { latestSdkVersion } from '../src/lib/docs/registry.ts';
import { readFileSync, writeFileSync } from 'node:fs';
import { existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Writes the two generated halves of `/docs/reference/compatibility` (TI-75).
 *
 *   node scripts/generate-compat.ts           write them
 *   node scripts/generate-compat.ts --check   fail if what is committed is stale
 *
 * ## Why partials rather than a component
 *
 * `content/docs/_partials/` is the mechanism guide content already has for
 * splicing in text written once and used elsewhere, and `:::include` resolves
 * on the raw markdown before rendering. A generated partial therefore goes
 * through the same parser, the same link check, the same heading anchors and
 * the same em dash gate as anything hand-written, with no second rendering
 * path. See `src/lib/docs/compat.ts` for what goes in them.
 *
 * ## Why the output is committed
 *
 * `pnpm check:docs`, `pnpm test` and `pnpm build` all render the page, and each
 * has to be runnable on a clean checkout without a generation step having been
 * remembered first. The build regenerates them anyway, before `check-docs`, so
 * a stale commit cannot deploy; `--check` is what makes it visible in CI rather
 * than silently corrected.
 *
 * Both inputs are files in this repository, so this is offline and
 * deterministic: the same commit generates the same bytes.
 */

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const PARTIALS = join(ROOT, 'content/docs/_partials');

const check = process.argv.includes('--check');

const version = latestSdkVersion();
if (!version) {
  console.error('No compiled SDK version under registry/sdk/, so there is nothing to generate.');
  process.exit(1);
}

const matrix = readMatrix(version);
if (!matrix) {
  console.error(`registry/sdk/${version} has no compiled API index.`);
  process.exit(1);
}

/** Says where a partial came from, in the file, for whoever opens it to edit it. */
const banner = (from: string) =>
  `<!-- Generated by scripts/generate-compat.ts from ${from}. Do not edit by hand: run \`pnpm docs:compat\`. -->`;

const toolchains = readToolchains();

const files: { name: string; body: string }[] = [
  {
    name: 'platform-support.md',
    body: `${renderMatrix(matrix, banner(`registry/sdk/${version}`))}`,
  },
  {
    name: 'toolchain.md',
    body: renderToolchain(toolchains, banner('registry/sdk/*/toolchain.json')),
  },
];

let stale = 0;

for (const { name, body } of files) {
  const path = join(PARTIALS, name);
  const rel = relative(ROOT, path);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;

  if (current === body) {
    console.log(`${rel} up to date`);
    continue;
  }
  if (check) {
    console.error(`${rel} is stale`);
    stale++;
    continue;
  }
  writeFileSync(path, body);
  console.log(`${rel} written`);
}

console.log(
  `\nSDK ${version}: ${matrix.rows.length} types, ` +
    `${matrix.members.toLocaleString('en-US')} members, ` +
    `${toolchains.length} release(s) with a captured toolchain`
);

if (!toolchains.length) {
  console.error('\nNo toolchain.json anywhere. Run: node scripts/capture-toolchain.ts');
  process.exit(1);
}

if (stale) {
  console.error(`\n${stale} partial(s) behind the registry. Run: pnpm docs:compat`);
  process.exit(1);
}
